# Generated by Django 4.0.6 on 2022-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('movimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_de_cuenta', models.IntegerField(blank=True, null=True)),
                ('monto', models.TextField(blank=True, null=True)),
                ('tipo_de_operacion', models.TextField(blank=True, null=True)),
                ('hora', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='TiposDeCuenta',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.TextField()),
            ],
            options={
                'db_table': 'tipos_de_cuenta',
            },
        ),
    ]
