# Generated by Django 4.0.6 on 2022-08-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('marca_id', models.TextField(primary_key=True, serialize=False)),
                ('nombre_tarjeta', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
