# Generated by Django 4.0.6 on 2022-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeCliente',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.TextField()),
                ('tarjetas_de_debito', models.TextField(blank=True, null=True)),
                ('caja_de_ahorro_usd', models.TextField()),
                ('descubierto', models.IntegerField()),
                ('tarjetas_de_credito', models.IntegerField()),
                ('retiro_de_efectivo', models.IntegerField()),
                ('chequeras', models.IntegerField()),
                ('comision_por_transferencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_transferencias', models.IntegerField(blank=True, null=True)),
                ('max_prestamo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_de_cliente',
                'managed': False,
            },
        ),
    ]
